language: node_js
node_js:
  - "4"
  - "5"
  - "6"
sudo: false
before_install: npm i -g npm@latest
install: 
  - npm i --ignore-scripts 
  - node ./node_modules/flow-bin/lib/install.js
after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'
